name: gnome-contacts
adopt-info: gnome-contacts
summary: A contacts manager for GNOME
description: |

  Contacts keeps and organize your contacts information. You can create,
  edit, delete and link together pieces of information about your contacts.
  Contacts aggregates the details from all your sources providing a
  centralized place for managing your contacts.

  Contacts will also integrate with online address books and automatically
  link contacts from different online sources.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict
base: core18

passthrough:
  layout:
    /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/folks/43/backends:
      symlink: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/folks/43/backends
    /usr/lib/evolution:
      symlink: $SNAP/usr/lib/evolution
    /usr/lib/evolution-data-server:
      symlink: $SNAP/usr/lib/evolution-data-server

plugs:
  gnome-3-28-1804:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-3-28-1804
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes

slots:
  # for GtkApplication registration
  gnome-contacts:
    interface: dbus
    bus: session
    name: org.gnome.Contacts

apps:
  gnome-contacts:
    command: desktop-launch gnome-contacts
    desktop: usr/share/applications/org.gnome.Contacts.desktop
    environment:
      GSETTINGS_SCHEMA_DIR: $SNAP/usr/share/glib-2.0/schemas
    plugs:
      - browser-support
      - desktop
      - desktop-legacy
      - gsettings
      - home
      - network
      - opengl
      - unity7
      - wayland
      - accounts-service
      - contacts-service
      # Not needed without cheese
      #- camera
      #- pulseaudio

parts:
  desktop-gnome-platform:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk3"]
    build-packages:
      - build-essential
      - libgtk-3-dev
    override-build: |
      snapcraftctl build
      mkdir -pv $SNAPCRAFT_PART_INSTALL/gnome-platform
  gnome-contacts:
    after: [desktop-gnome-platform]
    source: https://gitlab.gnome.org/GNOME/gnome-contacts.git
    source-type: git
    source-branch: gnome-3-30
    plugin: meson
    meson-parameters: 
      - --prefix=/usr
      - -Ddocs=false
      - -Dmanpage=false
      - -Dtelepathy=false
      - -Dcheese=false
    organize:
      snap/gnome-contacts/current/usr: usr
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version $(git describe --tags --abbrev=10)
    build-packages:
      - gettext
      - libebook1.2-dev
      - libedataserver1.2-dev
      - libedataserverui1.2-dev
      - libfolks-dev
      - libfolks-eds-dev
      - libgee-0.8-dev
      - libchamplain-0.12-dev
      #- libcheese-gtk-dev
      - libclutter-gtk-1.0-dev
      - libgeocode-glib-dev
      - libglib2.0-dev
      - libgnome-desktop-3-dev
      - libgoa-1.0-dev
      - libgirepository1.0-dev
      - libgtk-3-dev
      - valac
    stage-packages:
      - libchamplain-0.12-0
      - libgdata22
      - libgee-0.8-2
      - libgoa-1.0-0b
      #- libcheese8
      #- libcheese-gtk25
      - libgpm2
      - libical2
      - gstreamer1.0-plugins-good
      - libfolks25
      - libfolks-eds25
      - evolution-data-server
      - libedataserver-1.2-23
      - libedataserverui-1.2-2
      - libebook-1.2-19
      - libcamel-1.2-61
      - libedata-book-1.2-25
      - libphonenumber7
      - libebackend-1.2-10
      - libprotobuf10
      - libboost-system1.65.1
      - libboost-thread1.65.1
      - libstdc++6
      - liblz4-1

    prime:
      #- usr/lib/*/*cheese*.so.*
      - usr/lib/*/*gdata*.so.*
      - usr/lib/*/*ical*.so.*
      - usr/lib/*/*gee*.so.*
      - usr/lib/*/*goa*.so.*
      - usr/lib/*/*gpm*.so.*
      - usr/lib/*/*nss*.so
      - usr/lib/*/libsmime3.so
      - usr/lib/*/libssl3.so
      - usr/lib/*/libnspr4.so
      - usr/lib/*/liboauth.so.*
      - usr/lib/*/libpl*.so
      - usr/lib/*/*curl*.so.*
      - usr/lib/*/*rtmp.so.*
      - usr/lib/*/liblber-2.4.so.*
      - usr/lib/*/libldap_r-2.4.so.*
      - usr/lib/*/libsasl2.so.*
      - usr/lib/*/libgssapi.so.*
      - usr/lib/*/libheimntlm.so.*
      - usr/lib/*/libkrb5.so.*
      - usr/lib/*/libasn1.so.*
      - usr/lib/*/libhcrypto.so.*
      - usr/lib/*/libroken.so.*
      - usr/lib/*/libwind.so.*
      - usr/lib/*/libheimbase.so.*
      - usr/lib/*/libhx509.so.*
      - usr/lib/*/libfolks.so.*
      - usr/lib/*/libfolks-eds*.so.*
      - usr/lib/*/libedataserver*.so.*
      - usr/lib/*/libebook-*.so.*
      - usr/lib/*/libcamel-*.so.*
      - usr/lib/*/libedata-book-*.so.*
      - usr/lib/*/libphonenumber.so.*
      - usr/lib/*/libebackend-*.so.*
      - usr/lib/*/libprotobuf.so.*
      - usr/lib/*/libboost_system.so.*
      - usr/lib/*/libboost_thread.so.*
      - usr/lib/*/libstdc++.so.*
      - usr/lib/*/liblz4.so.*
      - usr/lib/*.so.*
      - usr/lib/evolution/*
      - usr/lib/evolution-data-server/*
      - usr/lib/*/folks/*
      - usr/share/*
      - usr/bin/*
