name: gnome-contacts
version: 3.22.1
summary: A contacts manager for GNOME
description: |

  Contacts keeps and organize your contacts information. You can create,
  edit, delete and link together pieces of information about your contacts.
  Contacts aggregates the details from all your sources providing a
  centralized place for managing your contacts.

  Contacts will also integrate with online address books and automatically
  link contacts from different online sources.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: classic

apps:
  gnome-contacts:
    command: bin/classic-launch classic ${SNAP}/usr/bin/gnome-contacts
    desktop: usr/share/applications/org.gnome.Contacts.desktop
    environment:
      GSETTINGS_SCHEMA_DIR: $SNAP/usr/share/glib-2.0/schemas
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/lib/gnome-contacts

parts:
  gnome-contacts:
    after: [desktop-gtk3]
    source: https://git.gnome.org/browse/gnome-contacts
    source-type: git
    source-branch: master
    #source-tag: 3.22.1
    plugin: autotools
    # workaround the issue described in https://launchpad.net/bugs/1583250
    configflags: ['LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro', --prefix=/snap/gnome-contacts/current/usr, --disable-fatal-warnings]
    organize:
      snap/gnome-contacts/current/usr: usr
    install: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp data/org.gnome.Contacts.desktop $SNAPCRAFT_PART_INSTALL/meta/gui/
    stage-packages:
      - evolution-data-server-common
      - evolution-data-server
      - folks-common
      - libfolks-eds25
    build-packages:
      - gnome-common
      - libebook1.2-dev
      - libedataserver1.2-dev
      - libedataserverui1.2-dev
      - libfolks-dev
      - libfolks-eds-dev
      - libfolks-telepathy-dev
      - libgee-0.8-dev
      - libchamplain-0.12-dev
      - libcheese-gtk-dev
      - libclutter-gtk-1.0-dev
      - libgeocode-glib-dev
      - libglib2.0-dev
      - libgnome-desktop-3-dev
      - libgoa-1.0-dev
      - libgirepository1.0-dev
      - libgtk-3-dev
      - libtelepathy-glib-dev
      - valac
  classic-launch:
    plugin: dump
    source: .
    organize:
      classic-launch: bin/classic-launch
