name: gnome-contacts
version: 3.22.1
summary: A contacts manager for GNOME
description: |

  Contacts keeps and organize your contacts information. You can create,
  edit, delete and link together pieces of information about your contacts.
  Contacts aggregates the details from all your sources providing a
  centralized place for managing your contacts.

  Contacts will also integrate with online address books and automatically
  link contacts from different online sources.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: classic

apps:
  gnome-contacts:
    command: bin/classic-launch classic ${SNAP}/usr/bin/gnome-contacts
    desktop: usr/share/applications/org.gnome.Contacts.desktop
    environment:
      GSETTINGS_SCHEMA_DIR: $SNAP/usr/share/glib-2.0/schemas

parts:
  evolution-data-server:
    after: [desktop-gtk3]
    source: https://git.gnome.org/browse/evolution-data-server
    source-type: git
    source-tag: EVOLUTION_DATA_SERVER_3_24_4
    plugin: cmake
    # workaround the issue described in https://launchpad.net/bugs/1583250
    configflags: [-DCMAKE_INSTALL_PREFIX=/snap/gnome-contacts/current/usr, -DENABLE_GOA=ON, -DENABLE_UOA=OFF, -DENABLE_WEATHER=OFF, -DENABLE_VALA_BINDINGS=ON, -DENABLE_INTROSPECTION=ON]
    organize:
      snap/gnome-contacts/current/usr: usr
    build-packages:
      - libtool
      - intltool
      - libdb-dev
      - libglib2.0-dev
      - libglib2.0-doc
      - libgdata-dev
      - libgirepository1.0-dev
      - libsecret-1-dev
      - libgcr-3-dev
      - libgoa-1.0-dev
      - libgtk-3-dev
      - libical-dev
      - libicu-dev
      - libjson-glib-dev
      - libkrb5-dev
      - libldap2-dev
      - liboauth-dev
      - librest-dev
      - libnss3-dev
      - libnspr4-dev
      - libsoup2.4-dev
      - libsqlite3-dev
      - libwebkit2gtk-4.0-dev
      - libxml2-dev
      - gtk-doc-tools
      - gobject-introspection
      - gperf
      - gnome-pkg-tools
      - pkg-config
      - valac
      - gnome-common
      - db-util
      - dbus
  folks:
    after: [evolution-data-server]
    source: https://git.gnome.org/browse/folks
    source-type: git
    source-tag: 0.11.4
    plugin: autotools
    # workaround the issue described in https://launchpad.net/bugs/1583250
    configflags: ['CFLAGS=-I/usr/include/evolution-data-server -I/usr/include', --prefix=/snap/gnome-contacts/current/usr, --enable-vala, --enable-eds-backend, --disable-telepathy-backend, --disable-ofono-backend, --disable-bluez-backend, --disable-modular-tests, --disable-fatal-warnings]
    organize:
      snap/gnome-contacts/current/usr: usr
    build-packages:
      - gnome-common
      - autotools-dev
      - intltool
      - libglib2.0-dev
      - libdbus-glib-1-dev
      - gobject-introspection
      - libgirepository1.0-dev
      - libgee-0.8-dev
      - libxml2-dev
      - libncurses5-dev
      - libreadline-dev
      - libebook1.2-dev
      - libebook-contacts1.2-dev
      - libedataserver1.2-dev
      - libedataserverui1.2-dev
      - valac
  gnome-contacts:
    after: [folks]
    source: https://git.gnome.org/browse/gnome-contacts
    source-type: git
    source-branch: master
    #source-tag: 3.22.1
    plugin: autotools
    # workaround the issue described in https://launchpad.net/bugs/1583250
    configflags: ['CFLAGS=-I/usr/include/evolution-data-server -I/usr/include', 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro', --prefix=/snap/gnome-contacts/current/usr, --disable-fatal-warnings]
    organize:
      snap/gnome-contacts/current/usr: usr
    install: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp data/org.gnome.Contacts.desktop $SNAPCRAFT_PART_INSTALL/meta/gui/
    build-packages:
      - gnome-common
      - libebook1.2-dev
      - libedataserver1.2-dev
      - libedataserverui1.2-dev
      - libfolks-dev
      - libfolks-eds-dev
      - libfolks-telepathy-dev
      - libgee-0.8-dev
      - libchamplain-0.12-dev
      - libcheese-gtk-dev
      - libclutter-gtk-1.0-dev
      - libgeocode-glib-dev
      - libglib2.0-dev
      - libgnome-desktop-3-dev
      - libgoa-1.0-dev
      - libgirepository1.0-dev
      - libgtk-3-dev
      - libtelepathy-glib-dev
      - valac
  classic-launch:
    plugin: dump
    source: .
    organize:
      classic-launch: bin/classic-launch
